services:
  catalog:
    build:
      context: ./services/catalog-service
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    command: npm run start:dev
    volumes:
      - ./services/catalog-service:/app
      - /app/node_modules

  auth:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    command: npm run start:dev
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules

  cart:
    build:
      context: ./services/cart-service
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    command: npm run start:dev
    volumes:
      - ./services/cart-service:/app
      - /app/node_modules
