apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: anloca
type: Opaque
stringData:
  database-url: "postgresql://developer:password123@postgres-auth:5431/myapp_dev?schema=public"
