version: "3.8"

services:
  postgres-cart:
    image: postgres:15-alpine
    container_name: cart_postgres_dev
    environment:
      POSTGRES_DB: cart_db
      POSTGRES_USER: cart_user
      POSTGRES_PASSWORD: cart_password
    ports:
      - "5433:5432"   # conecta desde tu PC en localhost:5433
    volumes:
      - cart_postgres_data:/var/lib/postgresql/data
    networks:
      - cart-network

  pgadmin-cart:
    image: dpage/pgadmin4
    container_name: cart_pgadmin_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5051:80"     # abre http://localhost:5051
    depends_on:
      - postgres-cart
    networks:
      - cart-network

volumes:
  cart_postgres_data:

networks:
  cart-network:
    driver: bridge
